export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

//
export const GET_BACKLOG = "DELETE_PROJECT";
export const GET_PROJECT_TASK = "DELETE_PROJECT";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT";
